# Generated by Django 5.2.8 on 2025-11-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("building_name", models.CharField(max_length=400)),
            ],
        ),
    ]
